### ISSUE TITLE
Time object can't be converted to Tod::TimeOfDay without require 'tod/core_extension'

### ISSUE THREAD

**Issue by willnet** [jackc/tod#22]
Is that right behavior?

```
irb(main):001:0> require 'tod'
=> true
irb(main):002:0> t = Time.new(2014, 2, 27, 12, 01, 02)
=> 2014-02-27 12:01:02 +0900
irb(main):003:0> tod = Tod::TimeOfDay(t)
ArgumentError: Invalid time of day string
	from /Users/maeshima/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/tod-2.0.0/lib/tod/time_of_day.rb:122:in `parse'
	from /Users/maeshima/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/tod-2.0.0/lib/tod/conversions.rb:8:in `TimeOfDay'
	from (irb):3
	from /Users/maeshima/.rbenv/versions/2.2.2/bin/irb:11:in `<main>'
irb(main):004:0> require 'date'
=> true
irb(main):005:0> require 'tod/core_extensions'
=> true
irb(main):006:0> tod = Tod::TimeOfDay(t)
=> #<Tod::TimeOfDay:0x007fbb0b82c468 @hour=12, @minute=1, @second=2, @second_of_day=43262>
```

**Comment by jackc** [comment]
Good catch. It was a bug. It's now fixed and v2.0.1 is now available on rubygems.org.
