### ISSUE TITLE
Does not work for me at least

### ISSUE THREAD

**Issue by kennyeni** [jackc/tod#23]
I have a model with:

```ruby
time_from :time
time_to :time
```

When saving gives: `TypeError: can't cast Tod::TimeOfDay to time`

Which obviously is because of serialization, if I add the lines to my model:

```ruby
serialize :time_from, Tod::TimeOfDay
serialize :time_to, Tod::TimeOfDay
```

It gives the following error:

```shell
NoMethodError: undefined method `empty?' for 2000-01-01 08:00:00 UTC:Time
	from /Users/Kenny/.tokaido/Gems/2.1.0/gems/tod-2.0.1/lib/tod/time_of_day.rb:172:in `load'
	from /Users/Kenny/.tokaido/Gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/type/serialized.rb:19:in `type_cast_from_database'
	from /Users/Kenny/.tokaido/Gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/type/mutable.rb:5:in `type_cast_from_user'
	from /Users/Kenny/.tokaido/Gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:100:in `type_cast'
	from /Users/Kenny/.tokaido/Gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:42:in `original_value'
	from /Users/Kenny/.tokaido/Gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:37:in `value'
	from /Users/Kenny/.tokaido/Gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute.rb:46:in `value_for_database'
	from /Users/Kenny/.tokaido/Gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:164:in `store_original_raw_attribute'
	from /Users/Kenny/.tokaido/Gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:93:in `write_attribute'
	from /Users/Kenny/.tokaido/Gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods.rb:50:in `__temp__4796d656f56627f6d6'
```

when trying to save the following object:

```ruby
{:day=>1, :time_from=>#<Tod::TimeOfDay:0x007f8813639a00 @hour=8, @minute=0, @second=0, @second_of_day=28800>, :time_to=>#<Tod::TimeOfDay:0x007f8813638fd8 @hour=15, @minute=0, @second=0, @second_of_day=54000>, :default_duration=>3600 seconds
```

**Comment by jackc** [comment]
Do you have failing code I can run? I've tried experimenting with the tests (https://github.com/jackc/tod/blob/master/test/tod/time_of_day_serializable_attribute_test.rb) for this feature, but I haven't been able to make it fail.

**Comment by kennyeni** [comment]
Well, I do have an example but it fails in the very basic ```MODEL.new(time_attr: Tod::TimeOfDay.new(8))``` call when serialization is required to a 'Time' field in the DB.

However, I found a very easy solution to this, just ```require 'tod/core_extensions'``` when using the serialization :)
